# Generated by Django 4.2.2 on 2023-07-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_initial'),
        ('District', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='districts', to='City.city'),
        ),
    ]
