# Generated by Django 4.2.2 on 2023-07-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('Doctor', '0002_alter_doctor_city_alter_doctor_district_and_more'),
        ('Review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctor_reviews', to='Doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patient_reviews', to='Patient.patient'),
        ),
    ]
