# Generated by Django 4.2.2 on 2023-07-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialization', '0002_initial'),
        ('City', '0002_initial'),
        ('District', '0003_alter_district_city'),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctorsByCity', to='City.city'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctorsByDistrict', to='District.district'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Specialization', to='Specialization.specialization'),
        ),
    ]
