# Generated by Django 4.2.2 on 2023-07-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('Appointment', '0003_alter_appointment_doctor'),
        ('Reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation_data', to='Appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='Patient.patient'),
        ),
    ]
